services:
  vector_store:
    container_name: qdrant_vector_store
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - vector_store:/qdrant/storage
    networks:
      - shared_net

  mlflow:
    container_name: mlflow_track_server
    image: ghcr.io/mlflow/mlflow
    command: mlflow server --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - mlruns:/mlruns
    networks:
      - shared_net

  postgres:
    container_name: postgres_db
    image: postgres:15
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared_net

  airflow-init:
      image: apache/airflow:2.10.2
      environment:
        - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
        - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
        - AIRFLOW__CORE__LOAD_EXAMPLES=True
        - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_USER}:${POSTGRES_PASSWORD}@postgres:5432/${AIRFLOW_DB}
      volumes:
        - ./airflow/dags:/opt/airflow/dags
        - ./airflow/logs:/opt/airflow/logs
        - ./airflow/plugins:/opt/airflow/plugins
      command: >
        bash -c "airflow db init"
      depends_on:
        - postgres
      networks:
        - shared_net

  airflow-webserver:
    image: apache/airflow:2.10.2
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=True
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_USER}:${POSTGRES_PASSWORD}@postgres:5432/${AIRFLOW_DB}
    command: webserver
    ports:
      - "8090:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    depends_on:
      - postgres
    restart: always
    networks:
      - shared_net

  airflow-scheduler:
    image: apache/airflow:2.10.2
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=True
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_USER}:${POSTGRES_PASSWORD}@postgres:5432/${AIRFLOW_DB}
    command: scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    depends_on:
      - postgres
    restart: always
    networks:
      - shared_net


volumes:
  mlruns:
    name: shared_infra_mlruns
  vector_store:
    name: shared_infra_vector_store
  pgdata:
    name: shared_infra_pgdata
networks:
  shared_net:
    external: true
